version: '2'
services:
   nginx-proxy:
     image: jwilder/nginx-proxy
     ports:
       - "8080:80"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
   db:
     image: mysql
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somecallupdashboard
       MYSQL_DATABASE: callup
       MYSQL_USER: callup
       MYSQL_PASSWORD: dbcalluppassword
   dashboard:
     build: .
     depends_on:
       - db
     ports:
       - "8000:8080"
     restart: always
     environment:
       VIRTUAL_HOST: whoami.local,intent-trainer.whoami.local,dashboard.callup.ai,intent-trainer.callup.ai
       VIRTUAL_PORT: 8080
       DAPTIN_DB_TYPE: mysql
       DAPTIN_DB_CONNECTION_STRING: callup:dbcalluppassword@tcp(db:3306)/callup
       DAPTIN_PORT: 8080
